### ISSUE TITLE
help for install please

### ISSUE THREAD

**Issue by kvonosan** [chrisjohndigital/TutorRoom#1]
I installed it:
git clone https://github.com/chrisjohndigital/TutorRoom.git
cd TutorRoom/
npm start

> tutorroom@1.0.0 start /root/TutorRoom
> node ./bin/www

module.js:471
    throw err;
    ^

Error: Cannot find module '/root/TutorRoom/bin/www'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

npm ERR! Linux 2.6.32-042stab120.19
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tutorroom@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tutorroom@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tutorroom package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tutorroom
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tutorroom
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/TutorRoom/npm-debug.log

please help me!

**Comment by kvonosan** [comment]
how to open in browser this application?

**Comment by chrisjohndigital** [comment]
Hi kvonosan, create an ejs app using express, then copy the content of the repo into the app, then run npm start. 

Regards, Chris.
